---
# tasks file for ansible-role-tftpd-openbsd

- name: Set tftpd_openbsd_flags
  service:
    name: "{{ tftpd_openbsd_service }}"
    arguments: "{{ tftpd_openbsd_flags }}"
    enabled: true
  notify:
    - Restart tftpd_openbsd_service

- name: Start tftpd_openbsd_service
  service:
    name: "{{ tftpd_openbsd_service }}"
    state: started
