---
# tasks file for ansible-role-tftpd-openbsd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ tftpd-openbsd_log_dir }}"
    mode: 0755
    owner: "{{ tftpd-openbsd_user }}"
    group: "{{ tftpd-openbsd_group }}"
    state: directory
  notify: Restart tftpd-openbsd

- name: Create db directory
  file:
    path: "{{ tftpd-openbsd_db_dir }}"
    mode: 0755
    owner: "{{ tftpd-openbsd_user }}"
    group: "{{ tftpd-openbsd_group }}"
    state: directory
  notify: Restart tftpd-openbsd

- name: Create tftpd-openbsd.conf
  template:
    src: tftpd-openbsd.conf.j2
    dest: "{{ tftpd-openbsd_conf_file }}"
    validate: echo %s
  notify: Restart tftpd-openbsd

- name: Start tftpd-openbsd
  service:
    name: "{{ tftpd-openbsd_service }}"
    enabled: true
    state: started
